"""initial schema

Revision ID: 7a0915392f8c
Revises: 
Create Date: 2026-09-15 10:51:00.240507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0915392f8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('employment_tenure_months', sa.Integer(), nullable=False),
    sa.Column('relationship_months', sa.Integer(), nullable=False),
    sa.Column('bureau_score', sa.Integer(), nullable=False),
    sa.Column('active_loans', sa.Integer(), nullable=False),
    sa.Column('existing_monthly_emi', sa.Float(), nullable=False),
    sa.Column('foir', sa.Float(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('actual_default_label', sa.Integer(), nullable=True),
    sa.Column('actual_fraud_label', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_customer_id'), 'applications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('avg_monthly_credits', sa.Float(), nullable=False),
    sa.Column('salary_consistency', sa.Float(), nullable=False),
    sa.Column('cash_withdrawal_ratio', sa.Float(), nullable=False),
    sa.Column('monthly_transaction_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_application_id'), 'agent_events', ['application_id'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_application_id'), 'agreements', ['application_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_application_id'), 'audit_events', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('income_mismatch_ratio', sa.Float(), nullable=True),
    sa.Column('name_match', sa.Boolean(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_table('fraud_features',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('device_reuse_count_30d', sa.Integer(), nullable=False),
    sa.Column('applications_last_7d', sa.Integer(), nullable=False),
    sa.Column('location_mismatch', sa.Integer(), nullable=False),
    sa.Column('bank_account_age_months', sa.Integer(), nullable=False),
    sa.Column('document_anomaly_score', sa.Float(), nullable=False),
    sa.Column('income_mismatch_score', sa.Float(), nullable=False),
    sa.Column('fraud_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('human_review_cases',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('review_reason', sa.String(), nullable=False),
    sa.Column('agent_recommendation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_user_id', sa.String(), nullable=True),
    sa.Column('decided_by_user_name', sa.String(), nullable=True),
    sa.Column('decision_action', sa.String(), nullable=True),
    sa.Column('decision_reason_code', sa.String(), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('modified_offer_amount', sa.Float(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_human_review_cases_application_id'), 'human_review_cases', ['application_id'], unique=False)
    op.create_table('model_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_outputs_application_id'), 'model_outputs', ['application_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate_apr', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('monthly_installment', sa.Float(), nullable=False),
    sa.Column('processing_fee', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=False)
    op.create_table('policy_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('overall_pass', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_results_application_id'), 'policy_results', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_results_application_id'), table_name='policy_results')
    op.drop_table('policy_results')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_model_outputs_application_id'), table_name='model_outputs')
    op.drop_table('model_outputs')
    op.drop_index(op.f('ix_human_review_cases_application_id'), table_name='human_review_cases')
    op.drop_table('human_review_cases')
    op.drop_table('fraud_features')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_application_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agreements_application_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_agent_events_application_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_customer_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('customers')
    # ### end Alembic commands ###
