"""
One-time setup endpoint for environments with no shell access to the
database -- specifically, Vercel serverless functions talking to a
managed Postgres (Neon, etc.) that this deployment's own network can
reach even when a developer's local machine/sandbox can't (e.g. no psql
or Docker available, or the caller's network only permits HTTPS
egress). Creates the schema and loads the bundled dataset in one HTTPS
call.

Protected by a bearer token (ADMIN_BOOTSTRAP_TOKEN env var) that must be
set for this endpoint to do anything at all -- with no token configured,
every call is refused. Treat the token as a credential: set a long random
value, and consider rotating/removing it after the one-time bootstrap.

Schema is created via SQLAlchemy's metadata directly (Base.metadata.
create_all), not the Alembic CLI -- there's no shell to invoke `alembic
upgrade head` from here. This produces the identical schema (the
Alembic migration was autogenerated from these same models), but the
`alembic_version` table won't reflect it. If you later point a normal
Alembic-aware environment at this same database, run `alembic stamp
head` first so Alembic knows it's already current.
"""

from __future__ import annotations

from fastapi import APIRouter, Header, HTTPException
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

from app.core.config import settings
from app.db.base import Base, engine
from app.services.data_loader import load_all

router = APIRouter(prefix="/admin", tags=["admin"])


def _require_token(x_admin_token: str | None):
    if not settings.admin_bootstrap_token:
        raise HTTPException(status_code=403, detail="Admin bootstrap is not enabled (ADMIN_BOOTSTRAP_TOKEN not set)")
    if x_admin_token != settings.admin_bootstrap_token:
        raise HTTPException(status_code=403, detail="Invalid admin token")


@router.post("/bootstrap")
def bootstrap(reset: bool = False, x_admin_token: str | None = Header(default=None)):
    _require_token(x_admin_token)

    logs: list[str] = []
    Base.metadata.create_all(engine)
    logs.append("Schema created (Base.metadata.create_all).")

    try:
        counts = load_all(engine, reset=reset, log=logs.append)
    except IntegrityError as exc:
        raise HTTPException(
            status_code=409,
            detail=(
                "Data already loaded (unique-key conflict on insert) -- "
                "call again with ?reset=true to wipe and reload, or leave "
                "as-is if this database is already seeded. "
                f"Underlying error: {exc.orig}"
            ),
        ) from exc

    return {"status": "ok", "counts": counts, "log": logs}


@router.post("/migrate")
def migrate(x_admin_token: str | None = Header(default=None)):
    """Patches columns onto tables that already existed before this
    release (create_all only creates missing tables, it never alters
    existing ones -- see the module docstring). Each statement uses
    IF NOT EXISTS so re-running this is always safe."""
    _require_token(x_admin_token)

    statements = [
        "ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_url VARCHAR",
        "ALTER TABLE documents ADD COLUMN IF NOT EXISTS extracted_fields JSON",
    ]
    logs: list[str] = []
    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(stmt))
            logs.append(stmt)

    return {"status": "ok", "log": logs}


@router.get("/status")
def status(x_admin_token: str | None = Header(default=None)):
    _require_token(x_admin_token)
    from sqlalchemy import func, select
    from sqlalchemy.orm import Session

    from app.db import models as m

    with Session(engine) as session:
        return {
            "customers": session.scalar(select(func.count()).select_from(m.Customer)),
            "applications": session.scalar(select(func.count()).select_from(m.Application)),
            "documents": session.scalar(select(func.count()).select_from(m.Document)),
            "human_review_cases": session.scalar(select(func.count()).select_from(m.HumanReviewCase)),
        }
